// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdavnliutrtsivqlqbeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkYXZubGl1dHJ0c2l2cWxxYmVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4Nzc1NDgsImV4cCI6MjA3MjQ1MzU0OH0.ak0kmizRQdxtUkMjNJgJU0Yq0l56hxujGur5tWDGVSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});